<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class CurriculumSeeder extends Seeder
{
    public function run()
    {
        $curriculums = [
            ['id' => 1, 'Cod' => '011A', 'Curriculum' => 'PLAN DE ESTUDIOS AGRONOMIA', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 2, 'Cod' => '011B', 'Curriculum' => 'PLAN DE ESTUDIOS CONVENIO DE LA ESCUELA PROFESIONAL DE AGRONOMIA', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 3, 'Cod' => '011C', 'Curriculum' => 'PLAN DE ESTUDIOS AGRONOMIA FILIAL YURIMAGUAS', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 4, 'Cod' => '011D', 'Curriculum' => 'PLAN DE ESTUDIOS CONVENIO DE LA ESCUELA PROFESIONAL DE AGRONOMIA', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 5, 'Cod' => '011E', 'Curriculum' => 'PLAN DE ESTUDIOS AGRONOMIA 2015', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 6, 'Cod' => '011F', 'Curriculum' => 'AGRONOMIA 2024', 'Id_Escuela' => 1, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'MSALAS'],
            ['id' => 7, 'Cod' => '012A', 'Curriculum' => 'PLAN DE ESTUDIOS GESTION AMBIENTAL', 'Id_Escuela' => 2, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 8, 'Cod' => '012B', 'Curriculum' => 'PLAN DE ESTUDIOS GESTION AMBIENTAL 2015', 'Id_Escuela' => 2, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 9, 'Cod' => '012C', 'Curriculum' => 'INGENIERÍA EN GESTIÓN AMBIENTAL', 'Id_Escuela' => 2, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'LCORAL146'],
            ['id' => 10, 'Cod' => '021A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ADMINISTRACIÓN', 'Id_Escuela' => 3, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 11, 'Cod' => '021B', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ADMINISTRACION-2015', 'Id_Escuela' => 3, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 12, 'Cod' => '021C', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ADMINISTRACIÓN - 2025', 'Id_Escuela' => 3, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'LCORAL146'],
            ['id' => 13, 'Cod' => '022A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE CONTABILIDAD', 'Id_Escuela' => 4, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 14, 'Cod' => '022B', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE CONTABILIDAD-2015', 'Id_Escuela' => 4, 'activo' => true, 'created_by' => null, 'updated_by' => '73486442'],
            ['id' => 15, 'Cod' => '022C', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE CONTABILIDAD-2024', 'Id_Escuela' => 4, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 16, 'Cod' => '023A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ECONOMIA', 'Id_Escuela' => 5, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 17, 'Cod' => '023B', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ECONOMIA-2015', 'Id_Escuela' => 5, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 18, 'Cod' => '023C', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE ECONOMIA-2024', 'Id_Escuela' => 5, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 19, 'Cod' => '024A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA ESCUELA PROFESIONAL DE NEGOCIOS INTERN. Y TURISMO', 'Id_Escuela' => 6, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 20, 'Cod' => '024B', 'Curriculum' => 'PLAN DE ESTUDIOS DE NEGOCIOS INTERN. Y TURISMO-2015', 'Id_Escuela' => 6, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 21, 'Cod' => '024C', 'Curriculum' => 'PLAN DE ESTUDIOS DE NEGOCIOS INTERN. Y TURISMO-2024', 'Id_Escuela' => 6, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => null],
            ['id' => 22, 'Cod' => '031A', 'Curriculum' => 'PLAN DE ESTUDIOS CIENCIAS BIOLOGICAS', 'Id_Escuela' => 7, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 23, 'Cod' => '031B', 'Curriculum' => 'PLAN DE ESTUDIOS CIENCIAS BIOLOGICAS-2015', 'Id_Escuela' => 7, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 24, 'Cod' => '031C', 'Curriculum' => 'PLAN DE ESTUDIOS CIENCIAS BIOLOGICAS-2024', 'Id_Escuela' => 7, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 25, 'Cod' => '032A', 'Curriculum' => 'PLAN DE ESTUDIOS ACUICULTURA', 'Id_Escuela' => 8, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 26, 'Cod' => '032B', 'Curriculum' => 'PLAN DE ESTUDIOS ACUICULTURA-2015', 'Id_Escuela' => 8, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 27, 'Cod' => '032C', 'Curriculum' => 'PLAN DE ESTUDIOS ACUICULTURA-2024', 'Id_Escuela' => 8, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 28, 'Cod' => '040A', 'Curriculum' => 'CARRERA: ANTROPOLOGÍA SOCIAL (2009)', 'Id_Escuela' => 9, 'activo' => true, 'created_by' => null, 'updated_by' => '73486442'],
            ['id' => 29, 'Cod' => '040B', 'Curriculum' => 'ANTROPOLOGIA SOCIAL 2024', 'Id_Escuela' => 9, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => null],
            ['id' => 30, 'Cod' => '041A', 'Curriculum' => 'CARRERA: EDUCACIÓN INICIAL (2009)', 'Id_Escuela' => 10, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 31, 'Cod' => '041AA', 'Curriculum' => 'PLAN DE ESTUDIOS INICIAL ANTIGUO', 'Id_Escuela' => 10, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'Cosme_Fulanito666'],
            ['id' => 32, 'Cod' => '041B', 'Curriculum' => 'CARRERA: EDUCACIÓN INICIAL (2016)', 'Id_Escuela' => 10, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 33, 'Cod' => '041C', 'Curriculum' => 'CARRERA: EDUCACIÓN INICIAL (2024)', 'Id_Escuela' => 10, 'activo' => true, 'created_by' => 'MILICHISPITA', 'updated_by' => 'MILICHISPITA'],
            ['id' => 34, 'Cod' => '042A', 'Curriculum' => 'CARRERA: EDUCACIÓN FÍSICA (2009)', 'Id_Escuela' => 11, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 35, 'Cod' => '042AA', 'Curriculum' => 'EDUCACIÓN FÍSICA (ANTIGUO)', 'Id_Escuela' => 11, 'activo' => true, 'created_by' => 'superadmin', 'updated_by' => 'MGUADALUPE150'],
            ['id' => 36, 'Cod' => '042B', 'Curriculum' => 'EDUCACIÓN FÍSICA CON MENCIÓN EN FORMACIÓN DEPORTIVA', 'Id_Escuela' => 11, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 37, 'Cod' => '042C', 'Curriculum' => 'CARRERA: EDUCACIÓN FÍSICA (2024)', 'Id_Escuela' => 11, 'activo' => true, 'created_by' => 'MILICHISPITA', 'updated_by' => null],
            ['id' => 38, 'Cod' => '043A', 'Curriculum' => 'CARRERA: EDUCACIÓN PRIMARIA (2009)', 'Id_Escuela' => 12, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 39, 'Cod' => '043AA', 'Curriculum' => 'PLAN DE ESTUDIOS PRIMARIA ANTIGUO', 'Id_Escuela' => 12, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 40, 'Cod' => '043B', 'Curriculum' => 'EDUCACIÓN PRIMARIA (2016)', 'Id_Escuela' => 12, 'activo' => true, 'created_by' => null, 'updated_by' => '73486442'],
            ['id' => 41, 'Cod' => '043C', 'Curriculum' => 'EDUCACIÓN PRIMARIA (2024)', 'Id_Escuela' => 12, 'activo' => true, 'created_by' => 'MILICHISPITA', 'updated_by' => null],
            ['id' => 42, 'Cod' => '044A', 'Curriculum' => 'CARRERA: MATEMÁTICA E INFORMÁTICA (2009)', 'Id_Escuela' => 13, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 43, 'Cod' => '044B', 'Curriculum' => 'CARRERA: MATEMÁTICA E INFORMÁTICA (2016)', 'Id_Escuela' => 13, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 44, 'Cod' => '044C', 'Curriculum' => 'CARRERA: MATEMÁTICA E INFORMÁTICA (2024)', 'Id_Escuela' => 13, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 45, 'Cod' => '045A', 'Curriculum' => 'CARRERA: CIENCIAS SOCIALES (2009)', 'Id_Escuela' => 14, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 46, 'Cod' => '045AA', 'Curriculum' => 'PLAN DE ESTUDIO DE CIENCIAS SOCIALES ANTIGUO ', 'Id_Escuela' => 14, 'activo' => true, 'created_by' => 'MGUADALUPE150', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 47, 'Cod' => '045B', 'Curriculum' => 'CARRERA: CIENCIAS SOCIALES (2016)', 'Id_Escuela' => 14, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 48, 'Cod' => '045C', 'Curriculum' => 'CARRERA: CIENCIAS SOCIALES 2024', 'Id_Escuela' => 14, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => null],
            ['id' => 49, 'Cod' => '046A', 'Curriculum' => 'CARRERA: LENGUA Y LITERATURA (2009)', 'Id_Escuela' => 15, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 50, 'Cod' => '046AA', 'Curriculum' => 'PLAN DE ESTUDIO DE LENGUA Y LITERATURA  ANTIGUO', 'Id_Escuela' => 15, 'activo' => true, 'created_by' => 'MGUADALUPE150', 'updated_by' => null],
            ['id' => 51, 'Cod' => '046B', 'Curriculum' => 'LENGUA Y LITERATURA (2016)', 'Id_Escuela' => 15, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 52, 'Cod' => '046C', 'Curriculum' => 'CARRERA: LENGUA Y LITERATURA 2024', 'Id_Escuela' => 15, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => null],
            ['id' => 53, 'Cod' => '047A', 'Curriculum' => 'CARRERA: FILOSOFÍA Y PSICOPEDAGOGÍA (2009)', 'Id_Escuela' => 16, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 54, 'Cod' => '047B', 'Curriculum' => 'CARRERA: FILOSOFÍA Y PSICOPEDAGOGÍA (2016)', 'Id_Escuela' => 16, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 55, 'Cod' => '047C', 'Curriculum' => 'CARRERA: FILOSOFÍA Y PSICOPEDAGOGÍA (2024)', 'Id_Escuela' => 16, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => 'Cosme_Fulanito666'],
            ['id' => 56, 'Cod' => '048A', 'Curriculum' => 'CARRERA: IDIOMAS EXTRANJEROS (2009)', 'Id_Escuela' => 17, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 57, 'Cod' => '048AA', 'Curriculum' => 'IDIOMAS EXTRANJEROS ANTIGUO', 'Id_Escuela' => 17, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'MSALAS'],
            ['id' => 58, 'Cod' => '048B', 'Curriculum' => 'CARRERA: IDIOMAS EXTRANJEROS (2016)', 'Id_Escuela' => 17, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 59, 'Cod' => '049A', 'Curriculum' => 'CARRERA: CIENCIAS NATURALES (2009)', 'Id_Escuela' => 18, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 60, 'Cod' => '049B', 'Curriculum' => 'CARRERA: CIENCIAS NATURALES (2016)', 'Id_Escuela' => 18, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 61, 'Cod' => '049C', 'Curriculum' => 'CIENCIAS NATURALES (2024)', 'Id_Escuela' => 18, 'activo' => true, 'created_by' => 'MILICHISPITA', 'updated_by' => null],
            ['id' => 62, 'Cod' => '051A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA FACULTAD DE ENFERMERÍA', 'Id_Escuela' => 19, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 63, 'Cod' => '051B', 'Curriculum' => 'PLAN DE ESTUDIOS DE ENFERMERIA - 2015', 'Id_Escuela' => 19, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 64, 'Cod' => '051C', 'Curriculum' => 'PLAN DE ESTUDIO DE ENFERMERIA - 2025', 'Id_Escuela' => 19, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'CGRANDEZ049'],
            ['id' => 65, 'Cod' => '051Z', 'Curriculum' => 'PLAN DE ESTUDIO DE ENFERMERIA ANTIGUO', 'Id_Escuela' => 19, 'activo' => true, 'created_by' => 'MGUADALUPE150', 'updated_by' => 'MGUADALUPE150'],
            ['id' => 66, 'Cod' => '052A', 'Curriculum' => 'COMPLEMENTACION ACADEMICA EDUCACION-ANTIGUO', 'Id_Escuela' => 20, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 67, 'Cod' => '052B', 'Curriculum' => 'COMPLEMENTACION ACADEMICA EDUCACION 2012', 'Id_Escuela' => 20, 'activo' => true, 'created_by' => 'superadmin', 'updated_by' => '72623049'],
            ['id' => 68, 'Cod' => '052C', 'Curriculum' => 'COMPLEMENTACION ACADEMICA EDUCACION 2013', 'Id_Escuela' => 20, 'activo' => true, 'created_by' => 'hans.laulate.649', 'updated_by' => 'hans.laulate.649'],
            ['id' => 69, 'Cod' => '052D', 'Curriculum' => 'COMPLEMENTACION PEDAGOGICO', 'Id_Escuela' => 20, 'activo' => true, 'created_by' => 'hans.laulate.649', 'updated_by' => null],
            ['id' => 70, 'Cod' => '052E', 'Curriculum' => 'COMPLEMENTACION ACADEMICA EDUCACION 2015', 'Id_Escuela' => 20, 'activo' => true, 'created_by' => null, 'updated_by' => '72623049'],
            ['id' => 71, 'Cod' => '061A', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA FORESTAL', 'Id_Escuela' => 21, 'activo' => true, 'created_by' => null, 'updated_by' => 'MILICHISPITA'],
            ['id' => 72, 'Cod' => '061B', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERÍA FORESTAL 2015', 'Id_Escuela' => 21, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 73, 'Cod' => '061C', 'Curriculum' => 'INGENIERIA FORESTAL 2024', 'Id_Escuela' => 21, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'Cosme_Fulanito666'],
            ['id' => 74, 'Cod' => '062A', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERÍA EN ECOLOGÍA DE BOSQUES TROPICALES', 'Id_Escuela' => 22, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 75, 'Cod' => '062B', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERÍA EN ECOLOGÍA DE BOSQUES TROPICALES 2015', 'Id_Escuela' => 22, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 76, 'Cod' => '062C', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERÍA EN ECOLOGÍA DE BOSQUES TROPICALES 2024', 'Id_Escuela' => 22, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => 'Cosme_Fulanito666'],
            ['id' => 77, 'Cod' => '063A', 'Curriculum' => 'PLAN BILINGUE INTERCULTURAL', 'Id_Escuela' => 23, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 78, 'Cod' => '063B', 'Curriculum' => 'PLAN BILINGUE INTERCULTURAL', 'Id_Escuela' => 23, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 79, 'Cod' => '063C', 'Curriculum' => 'EDUCACIÓN INICIAL INTERCULTURAL BILINGÜE', 'Id_Escuela' => 23, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'MSALAS'],
            ['id' => 80, 'Cod' => '063D', 'Curriculum' => 'EDUCACIÓN PRIMARIA INTERCULTURAL BILINGÜE', 'Id_Escuela' => 23, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => 'MSALAS'],
            ['id' => 81, 'Cod' => '064A', 'Curriculum' => 'PLAN DE ESTUDIO DE BIOLOGÍA QUÍMICA', 'Id_Escuela' => 24, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 82, 'Cod' => '065A', 'Curriculum' => 'MATEMÁTICA-FÍSICA', 'Id_Escuela' => 25, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 83, 'Cod' => '071A', 'Curriculum' => 'PLAN DE INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Id_Escuela' => 26, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 84, 'Cod' => '071B', 'Curriculum' => 'PLAN DE INGENIERIA EN INDUSTRIAS ALIMENTARIAS 2015', 'Id_Escuela' => 26, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 85, 'Cod' => '071C', 'Curriculum' => 'PLAN DE INGENIERIA EN INDUSTRIAS ALIMENTARIAS 2024', 'Id_Escuela' => 26, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => 'Cosme_Fulanito666'],
            ['id' => 86, 'Cod' => '071P', 'Curriculum' => 'PLAN DE INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Id_Escuela' => 26, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 87, 'Cod' => '072A', 'Curriculum' => 'PLAN DE ESTUDIOS DE BROMATOLOGÍA Y NUTRICIÓN HUMANA', 'Id_Escuela' => 27, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 88, 'Cod' => '072B', 'Curriculum' => 'PLAN DE BROMATOLOGÍA Y NUTRICIÓN HUMANA 2015', 'Id_Escuela' => 27, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 89, 'Cod' => '072C', 'Curriculum' => 'BROMATOLOGIA Y NUTRICION HUMANA 2024', 'Id_Escuela' => 27, 'activo' => true, 'created_by' => 'MSALAS', 'updated_by' => null],
            ['id' => 90, 'Cod' => '081A', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA QUIMICA', 'Id_Escuela' => 28, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 91, 'Cod' => '081B', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA QUIMICA 2015', 'Id_Escuela' => 28, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 92, 'Cod' => '081C', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA QUIMICA 2024', 'Id_Escuela' => 28, 'activo' => true, 'created_by' => 'Cosme_Fulanito666', 'updated_by' => null],
            ['id' => 93, 'Cod' => '081Z', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA QUIMICA-ANTIGUO', 'Id_Escuela' => 28, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 94, 'Cod' => '091A', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA FACULTAD DE MEDICINA HUMANA', 'Id_Escuela' => 29, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 95, 'Cod' => '091B', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA FACULTAD DE MEDICINA  - ANTIGUO', 'Id_Escuela' => 29, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 96, 'Cod' => '091C', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA FACULTAD DE MEDICINA HUMANA 2016', 'Id_Escuela' => 29, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 97, 'Cod' => '091D', 'Curriculum' => 'PLAN DE ESTUDIOS DE LA FACULTAD DE MEDICINA HUMANA-2024', 'Id_Escuela' => 29, 'activo' => true, 'created_by' => 'MILICHISPITA', 'updated_by' => null],
            ['id' => 98, 'Cod' => '101A', 'Curriculum' => 'PLAN DE ESTUDIO ZOOTECNIA', 'Id_Escuela' => 30, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 99, 'Cod' => '101B', 'Curriculum' => 'PLAN DE ESTUDIO ZOOTECNIA-2015', 'Id_Escuela' => 30, 'activo' => true, 'created_by' => null, 'updated_by' => 'MILICHISPITA'],
            ['id' => 100, 'Cod' => '101C', 'Curriculum' => 'PLAN DE ESTUDIO ZOOTECNIA-2024', 'Id_Escuela' => 30, 'activo' => true, 'created_by' => 'CGRANDEZ049', 'updated_by' => 'MSALAS'],
            ['id' => 101, 'Cod' => '111A', 'Curriculum' => 'PLAN DE ESTUDIOS FACULTAD DE DERECHO Y CIENCIAS POLITICAS', 'Id_Escuela' => 31, 'activo' => true, 'created_by' => null, 'updated_by' => 'CGRANDEZ049'],
            ['id' => 102, 'Cod' => '111B', 'Curriculum' => 'PLAN DE ESTUDIOS FACULTAD DE DERECHO Y CIENCIAS POLITICAS-2015', 'Id_Escuela' => 31, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 103, 'Cod' => '121A', 'Curriculum' => 'PLAN DE ESTUDIOS FARMACIA Y BIOQUÍMICA', 'Id_Escuela' => 32, 'activo' => true, 'created_by' => null, 'updated_by' => 'MGUADALUPE150'],
            ['id' => 104, 'Cod' => '121B', 'Curriculum' => '-', 'Id_Escuela' => 32, 'activo' => true, 'created_by' => null, 'updated_by' => '73486442'],
            ['id' => 105, 'Cod' => '121C', 'Curriculum' => 'PLAN DE ESTUDIOS FARMACIA Y BIOQUÍMICA 2015', 'Id_Escuela' => 32, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 106, 'Cod' => '131A', 'Curriculum' => 'PLAN DE ESTUDIOS DE SISTEMAS', 'Id_Escuela' => 33, 'activo' => true, 'created_by' => null, 'updated_by' => 'superadmin'],
            ['id' => 107, 'Cod' => '131B', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA DE SISTEMAS E INFORMÁTICA 2015', 'Id_Escuela' => 33, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 108, 'Cod' => '131C', 'Curriculum' => 'PLAN DE ESTUDIOS DE INGENIERIA DE SISTEMAS E INFORMÁTICA 2024', 'Id_Escuela' => 33, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => null],
            ['id' => 109, 'Cod' => '141A', 'Curriculum' => 'PLAN DE ESTUDIOS ODONTOLOGIA', 'Id_Escuela' => 34, 'activo' => true, 'created_by' => null, 'updated_by' => '41433150'],
            ['id' => 110, 'Cod' => '141B', 'Curriculum' => 'PLAN DE ESTUDIOS ODONTOLOGIA-2015', 'Id_Escuela' => 34, 'activo' => true, 'created_by' => null, 'updated_by' => 'hans.laulate.649'],
            ['id' => 111, 'Cod' => '141C', 'Curriculum' => 'PLAN DE ESTUDIOS ODONTOLOGÍA-2024', 'Id_Escuela' => 34, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'LCORAL146'],
            ['id' => 112, 'Cod' => '048B1', 'Curriculum' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y ALEMÁN', 'Id_Escuela' => 36, 'activo' => true, 'created_by' => 'superadmin', 'updated_by' => '72623049'],
            ['id' => 113, 'Cod' => '048C1', 'Curriculum' => 'CON ESPECIALIDAD EN INGLÉS Y ALEMÁN', 'Id_Escuela' => 36, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'LCORAL146'],
            ['id' => 114, 'Cod' => '048B2', 'Curriculum' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y FRANCÉS', 'Id_Escuela' => 37, 'activo' => true, 'created_by' => 'superadmin', 'updated_by' => '72623049'],
            ['id' => 115, 'Cod' => '048C2', 'Curriculum' => 'CON ESPECIALIDAD EN INGLÉS Y FRANCÉS', 'Id_Escuela' => 37, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => 'LCORAL146'],
            ['id' => 116, 'Cod' => '048B3', 'Curriculum' => 'CARRERA: IDIOMAS EXTRANJEROS CON MENCIÓN EN INGLÉS-PORTUGUÉS', 'Id_Escuela' => 38, 'activo' => true, 'created_by' => '41433150', 'updated_by' => 'superadmin'],
            ['id' => 117, 'Cod' => '048C3', 'Curriculum' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y PORTUGUÉS', 'Id_Escuela' => 38, 'activo' => true, 'created_by' => 'LCORAL146', 'updated_by' => null],
        ];

        DB::table('Tb_Curriculum')->insert($curriculums);
    }
}