<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class ProvinciaSeeder extends Seeder
{
    public function run()
    {
        $provincias = [
            ['id' => 101, 'Provincia' => 'CHACHAPOYAS', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 102, 'Provincia' => 'BAGUA', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 103, 'Provincia' => 'BONGARA', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 104, 'Provincia' => 'CONDORCANQUI', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 105, 'Provincia' => 'LUYA', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 106, 'Provincia' => 'RODRIGUEZ DE MENDOZA', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 107, 'Provincia' => 'UTCUBAMBA', 'activo' => true, 'id_departamento' => 1, 'created_by' => null, 'updated_by' => null],
            ['id' => 201, 'Provincia' => 'HUARAZ', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 202, 'Provincia' => 'AIJA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 203, 'Provincia' => 'ANTONIO RAYMONDI', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 204, 'Provincia' => 'ASUNCION', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 205, 'Provincia' => 'BOLOGNESI', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 206, 'Provincia' => 'CARHUAZ', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 207, 'Provincia' => 'CARLOS FERMIN FITZCA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 208, 'Provincia' => 'CASMA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 209, 'Provincia' => 'CORONGO', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 210, 'Provincia' => 'HUARI', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 211, 'Provincia' => 'HUARMEY', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 212, 'Provincia' => 'HUAYLAS', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 213, 'Provincia' => 'MARISCAL LUZURIAGA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 214, 'Provincia' => 'OCROS', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 215, 'Provincia' => 'PALLASCA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 216, 'Provincia' => 'POMABAMBA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 217, 'Provincia' => 'RECUAY', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 218, 'Provincia' => 'SANTA', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 219, 'Provincia' => 'SIHUAS', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 220, 'Provincia' => 'YUNGAY', 'activo' => true, 'id_departamento' => 2, 'created_by' => null, 'updated_by' => null],
            ['id' => 301, 'Provincia' => 'ABANCAY', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 302, 'Provincia' => 'ANDAHUAYLAS', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 303, 'Provincia' => 'ANTABAMBA', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 304, 'Provincia' => 'AYMARAES', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 305, 'Provincia' => 'COTABAMBAS', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 306, 'Provincia' => 'CHINCHEROS', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 307, 'Provincia' => 'GRAU', 'activo' => true, 'id_departamento' => 3, 'created_by' => null, 'updated_by' => null],
            ['id' => 401, 'Provincia' => 'AREQUIPA', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 402, 'Provincia' => 'CAMANA', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 403, 'Provincia' => 'CARAVELI', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 404, 'Provincia' => 'CASTILLA', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 405, 'Provincia' => 'CAYLLOMA', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 406, 'Provincia' => 'CONDESUYOS', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 407, 'Provincia' => 'ISLAY', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 408, 'Provincia' => 'LA UNION', 'activo' => true, 'id_departamento' => 4, 'created_by' => null, 'updated_by' => null],
            ['id' => 501, 'Provincia' => 'HUAMANGA', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 502, 'Provincia' => 'CANGALLO', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 503, 'Provincia' => 'HUANCA SANCOS', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 504, 'Provincia' => 'HUANTA', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 505, 'Provincia' => 'LA MAR', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 506, 'Provincia' => 'LUCANAS', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 507, 'Provincia' => 'PARINACOCHAS', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 508, 'Provincia' => 'PAUCAR DEL SARA SARA', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 509, 'Provincia' => 'SUCRE', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 510, 'Provincia' => 'VICTOR FAJARDO', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 511, 'Provincia' => 'VILCAS HUAMAN', 'activo' => true, 'id_departamento' => 5, 'created_by' => null, 'updated_by' => null],
            ['id' => 601, 'Provincia' => 'CAJAMARCA', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 602, 'Provincia' => 'CAJABAMBA', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 603, 'Provincia' => 'CELENDIN', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 604, 'Provincia' => 'CHOTA', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 605, 'Provincia' => 'CONTUMAZA', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 606, 'Provincia' => 'CUTERVO', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 607, 'Provincia' => 'HUALGAYOC', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 608, 'Provincia' => 'JAEN', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 609, 'Provincia' => 'SAN IGNACIO', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 610, 'Provincia' => 'SAN MARCOS', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 611, 'Provincia' => 'SAN MIGUEL', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 612, 'Provincia' => 'SAN PABLO', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 613, 'Provincia' => 'SANTA CRUZ', 'activo' => true, 'id_departamento' => 6, 'created_by' => null, 'updated_by' => null],
            ['id' => 701, 'Provincia' => 'CALLAO', 'activo' => true, 'id_departamento' => 7, 'created_by' => null, 'updated_by' => null],
            ['id' => 801, 'Provincia' => 'CUSCO', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 802, 'Provincia' => 'ACOMAYO', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 803, 'Provincia' => 'ANTA', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 804, 'Provincia' => 'CALCA', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 805, 'Provincia' => 'CANAS', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 806, 'Provincia' => 'CANCHIS', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 807, 'Provincia' => 'CHUMBIVILCAS', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 808, 'Provincia' => 'ESPINAR', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 809, 'Provincia' => 'LA CONVENCION', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 810, 'Provincia' => 'PARURO', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 811, 'Provincia' => 'PAUCARTAMBO', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 812, 'Provincia' => 'QUISPICANCHI', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 813, 'Provincia' => 'URUBAMBA', 'activo' => true, 'id_departamento' => 8, 'created_by' => null, 'updated_by' => null],
            ['id' => 901, 'Provincia' => 'HUANCAVELICA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 902, 'Provincia' => 'ACOBAMBA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 903, 'Provincia' => 'ANGARAES', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 904, 'Provincia' => 'CASTROVIRREYNA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 905, 'Provincia' => 'CHURCAMPA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 906, 'Provincia' => 'HUAYTARA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 907, 'Provincia' => 'TAYACAJA', 'activo' => true, 'id_departamento' => 9, 'created_by' => null, 'updated_by' => null],
            ['id' => 1001, 'Provincia' => 'HUANUCO', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1002, 'Provincia' => 'AMBO', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1003, 'Provincia' => 'DOS DE MAYO', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1004, 'Provincia' => 'HUACAYBAMBA', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1005, 'Provincia' => 'HUAMALIES', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1006, 'Provincia' => 'LEONCIO PRADO', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1007, 'Provincia' => 'MARAÑON', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1008, 'Provincia' => 'PACHITEA', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1009, 'Provincia' => 'PUERTO INCA', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1010, 'Provincia' => 'LAURICOCHA', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1011, 'Provincia' => 'YAROWILCA', 'activo' => true, 'id_departamento' => 10, 'created_by' => null, 'updated_by' => null],
            ['id' => 1101, 'Provincia' => 'ICA', 'activo' => true, 'id_departamento' => 11, 'created_by' => null, 'updated_by' => null],
            ['id' => 1102, 'Provincia' => 'CHINCHA', 'activo' => true, 'id_departamento' => 11, 'created_by' => null, 'updated_by' => null],
            ['id' => 1103, 'Provincia' => 'NAZCA', 'activo' => true, 'id_departamento' => 11, 'created_by' => null, 'updated_by' => null],
            ['id' => 1104, 'Provincia' => 'PALPA', 'activo' => true, 'id_departamento' => 11, 'created_by' => null, 'updated_by' => null],
            ['id' => 1105, 'Provincia' => 'PISCO', 'activo' => true, 'id_departamento' => 11, 'created_by' => null, 'updated_by' => null],
            ['id' => 1201, 'Provincia' => 'HUANCAYO', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1202, 'Provincia' => 'CONCEPCION', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1203, 'Provincia' => 'CHANCHAMAYO', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1204, 'Provincia' => 'JAUJA', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1205, 'Provincia' => 'JUNIN', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1206, 'Provincia' => 'SATIPO', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1207, 'Provincia' => 'TARMA', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1208, 'Provincia' => 'YAULI', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1209, 'Provincia' => 'CHUPACA', 'activo' => true, 'id_departamento' => 12, 'created_by' => null, 'updated_by' => null],
            ['id' => 1301, 'Provincia' => 'TRUJILLO', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1302, 'Provincia' => 'ASCOPE', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1303, 'Provincia' => 'BOLIVAR', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1304, 'Provincia' => 'CHEPEN', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1305, 'Provincia' => 'JULCAN', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1306, 'Provincia' => 'OTUZCO', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1307, 'Provincia' => 'PACASMAYO', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1308, 'Provincia' => 'PATAZ', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1309, 'Provincia' => 'SANCHEZ CARRION', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1310, 'Provincia' => 'SANTIAGO DE CHUCO', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1311, 'Provincia' => 'GRAN CHIMU', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1312, 'Provincia' => 'VIRU', 'activo' => true, 'id_departamento' => 13, 'created_by' => null, 'updated_by' => null],
            ['id' => 1401, 'Provincia' => 'CHICLAYO', 'activo' => true, 'id_departamento' => 14, 'created_by' => null, 'updated_by' => null],
            ['id' => 1402, 'Provincia' => 'FERREÑAFE', 'activo' => true, 'id_departamento' => 14, 'created_by' => null, 'updated_by' => null],
            ['id' => 1403, 'Provincia' => 'LAMBAYEQUE', 'activo' => true, 'id_departamento' => 14, 'created_by' => null, 'updated_by' => null],
            ['id' => 1501, 'Provincia' => 'LIMA', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1502, 'Provincia' => 'BARRANCA', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1503, 'Provincia' => 'CAJATAMBO', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1504, 'Provincia' => 'CANTA', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1505, 'Provincia' => 'CAÑETE', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1506, 'Provincia' => 'HUARAL', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1507, 'Provincia' => 'HUAROCHIRI', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1508, 'Provincia' => 'HUAURA', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1509, 'Provincia' => 'OYON', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1510, 'Provincia' => 'YAUYOS', 'activo' => true, 'id_departamento' => 15, 'created_by' => null, 'updated_by' => null],
            ['id' => 1601, 'Provincia' => 'MAYNAS', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1602, 'Provincia' => 'ALTO AMAZONAS', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1603, 'Provincia' => 'LORETO', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1604, 'Provincia' => 'MARISCAL RAMON CASTILLA', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1605, 'Provincia' => 'REQUENA', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1606, 'Provincia' => 'UCAYALI', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1607, 'Provincia' => 'DATEM DEL MARAÑON', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1608, 'Provincia' => 'MAYNAS2', 'activo' => true, 'id_departamento' => 16, 'created_by' => null, 'updated_by' => null],
            ['id' => 1701, 'Provincia' => 'TAMBOPATA', 'activo' => true, 'id_departamento' => 17, 'created_by' => null, 'updated_by' => null],
            ['id' => 1702, 'Provincia' => 'MANU', 'activo' => true, 'id_departamento' => 17, 'created_by' => null, 'updated_by' => null],
            ['id' => 1703, 'Provincia' => 'TAHUAMANU', 'activo' => true, 'id_departamento' => 17, 'created_by' => null, 'updated_by' => null],
            ['id' => 1801, 'Provincia' => 'MARISCAL NIETO', 'activo' => true, 'id_departamento' => 18, 'created_by' => null, 'updated_by' => null],
            ['id' => 1802, 'Provincia' => 'GENERAL SANCHEZ CERR', 'activo' => true, 'id_departamento' => 18, 'created_by' => null, 'updated_by' => null],
            ['id' => 1803, 'Provincia' => 'ILO', 'activo' => true, 'id_departamento' => 18, 'created_by' => null, 'updated_by' => null],
            ['id' => 1901, 'Provincia' => 'PASCO', 'activo' => true, 'id_departamento' => 19, 'created_by' => null, 'updated_by' => null],
            ['id' => 1902, 'Provincia' => 'DANIEL ALCIDES CARRI', 'activo' => true, 'id_departamento' => 19, 'created_by' => null, 'updated_by' => null],
            ['id' => 1903, 'Provincia' => 'OXAPAMPA', 'activo' => true, 'id_departamento' => 19, 'created_by' => null, 'updated_by' => null],
            ['id' => 2001, 'Provincia' => 'PIURA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2002, 'Provincia' => 'AYABACA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2003, 'Provincia' => 'HUANCABAMBA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2004, 'Provincia' => 'MORROPON', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2005, 'Provincia' => 'PAITA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2006, 'Provincia' => 'SULLANA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2007, 'Provincia' => 'TALARA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2008, 'Provincia' => 'SECHURA', 'activo' => true, 'id_departamento' => 20, 'created_by' => null, 'updated_by' => null],
            ['id' => 2101, 'Provincia' => 'PUNO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2102, 'Provincia' => 'AZANGARO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2103, 'Provincia' => 'CARABAYA', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2104, 'Provincia' => 'CHUCUITO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2105, 'Provincia' => 'EL COLLAO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2106, 'Provincia' => 'HUANCANE', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2107, 'Provincia' => 'LAMPA', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2108, 'Provincia' => 'MELGAR', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2109, 'Provincia' => 'MOHO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2110, 'Provincia' => 'SAN ANTONIO DE PUTIN', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2111, 'Provincia' => 'SAN ROMAN', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2112, 'Provincia' => 'SANDIA', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2113, 'Provincia' => 'YUNGUYO', 'activo' => true, 'id_departamento' => 21, 'created_by' => null, 'updated_by' => null],
            ['id' => 2201, 'Provincia' => 'MOYOBAMBA', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2202, 'Provincia' => 'BELLAVISTA', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2203, 'Provincia' => 'EL DORADO', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2204, 'Provincia' => 'HUALLAGA', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2205, 'Provincia' => 'LAMAS', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2206, 'Provincia' => 'MARISCAL CACERES', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2207, 'Provincia' => 'PICOTA', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2208, 'Provincia' => 'RIOJA', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2209, 'Provincia' => 'SAN MARTIN', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2210, 'Provincia' => 'TOCACHE', 'activo' => true, 'id_departamento' => 22, 'created_by' => null, 'updated_by' => null],
            ['id' => 2301, 'Provincia' => 'TACNA', 'activo' => true, 'id_departamento' => 23, 'created_by' => null, 'updated_by' => null],
            ['id' => 2302, 'Provincia' => 'CANDARAVE', 'activo' => true, 'id_departamento' => 23, 'created_by' => null, 'updated_by' => null],
            ['id' => 2303, 'Provincia' => 'JORGE BASADRE', 'activo' => true, 'id_departamento' => 23, 'created_by' => null, 'updated_by' => null],
            ['id' => 2304, 'Provincia' => 'TARATA', 'activo' => true, 'id_departamento' => 23, 'created_by' => null, 'updated_by' => null],
            ['id' => 2401, 'Provincia' => 'TUMBES', 'activo' => true, 'id_departamento' => 24, 'created_by' => null, 'updated_by' => null],
            ['id' => 2402, 'Provincia' => 'CONTRALMIRANTE VILLA', 'activo' => true, 'id_departamento' => 24, 'created_by' => null, 'updated_by' => null],
            ['id' => 2403, 'Provincia' => 'ZARUMILLA', 'activo' => true, 'id_departamento' => 24, 'created_by' => null, 'updated_by' => null],
            ['id' => 2501, 'Provincia' => 'CORONEL PORTILLO', 'activo' => true, 'id_departamento' => 25, 'created_by' => null, 'updated_by' => null],
            ['id' => 2502, 'Provincia' => 'ATALAYA', 'activo' => true, 'id_departamento' => 25, 'created_by' => null, 'updated_by' => null],
            ['id' => 2503, 'Provincia' => 'PADRE ABAD', 'activo' => true, 'id_departamento' => 25, 'created_by' => null, 'updated_by' => null],
            ['id' => 2504, 'Provincia' => 'PURUS', 'activo' => true, 'id_departamento' => 25, 'created_by' => null, 'updated_by' => null],
        ];

        DB::table('tb_provincia')->insert($provincias);
    }
}
