<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TbEscuelaSeeder extends Seeder
{
    public function run()
    {
        DB::table('Tb_Escuela')->insert([
            [
                'Escuela' => 'AGRONOMIA',
                'Id_facultad' => 1,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERIA EN GESTION AMBIENTAL',
                'Id_facultad' => 1,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ADMINISTRACIÓN',
                'Id_facultad' => 4,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'CONTABILIDAD',
                'Id_facultad' => 4,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ECONOMIA',
                'Id_facultad' => 4,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'NEGOCIOS INTERNACIONALES Y TURISMO',
                'Id_facultad' => 4,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'CIENCIAS BIOLOGICAS',
                'Id_facultad' => 2,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ACUICULTURA',
                'Id_facultad' => 2,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ANTROPOLOGÍA SOCIAL',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN INICIAL',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN FÍSICA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN PRIMARIA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: MATEMÁTICA E INFORMÁTICA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: CIENCIAS SOCIALES',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: LENGUA Y LITERATURA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: FILOSOFIA Y PSICOPEDAGOGÍA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: IDIOMAS EXTRANJEROS',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'SECUNDARIA: CIENCIAS NATURALES',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ENFERMERIA',
                'Id_facultad' => 7,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'COMPLEMENTACION ACADEMICA EDUCACION',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'superadmin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERIA FORESTAL',
                'Id_facultad' => 5,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERÍA EN ECOLOGÍA DE BOSQUES TROPICALES',
                'Id_facultad' => 5,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'BILINGÜE INTERCULTURAL',
                'Id_facultad' => 3,
                'activo' => false,
                'created_by' => null,
                'updated_by' => 'superadmin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'BIOLOGÍA QUÍMICA',
                'Id_facultad' => 3,
                'activo' => false,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'MATEMÁTICA-FÍSICA',
                'Id_facultad' => 3,
                'activo' => false,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERÍA EN INDUSTRIAS ALIMENTARIAS',
                'Id_facultad' => 9,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'BROMATOLOGÍA Y NUTRICIÓN HUMANA',
                'Id_facultad' => 9,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERIA QUIMICA',
                'Id_facultad' => 11,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'MEDICINA HUMANA',
                'Id_facultad' => 12,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ZOOTECNIA',
                'Id_facultad' => 14,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'DERECHO Y CIENCIAS POLITICAS',
                'Id_facultad' => 6,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'FARMACIA Y BIOQUÍMICA',
                'Id_facultad' => 8,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'INGENIERIA DE SISTEMAS E INFORMÁTICA',
                'Id_facultad' => 10,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'CGRANDEZ049',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'ODONTOLOGIA',
                'Id_facultad' => 13,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'PSICOLOGÍA',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => 'superadmin',
                'updated_by' => 'superadmin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y ALEMÁN',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y FRANCÉS',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
[
                'Escuela' => 'EDUCACIÓN SECUNDARIA CON ESPECIALIDAD EN INGLÉS Y PORTUGUÉS',
                'Id_facultad' => 3,
                'activo' => true,
                'created_by' => null,
                'updated_by' => 'jesus.hagiwara.812',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
